### ISSUE TITLE
RuntimeError: unexpected EOF, expected 120303 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by Janvi161945** [MuhammadMoinFaisal/YOLOv8_Segmentation_DeepSORT_Object_Tracking#11]
I have followed all the steps of installation and when I am running this 

```!python tracking_vehicle_counting.py model=yolov8l.pt source="test.mp4" show=True ```
**Error:** 
Error executing job with overrides: ['model=yolov8l.pt', 'source=/content/YOLOv8-Object-Detection-with-DeepSORT-Tracking/output_video.mp4', 'show=True']
Traceback (most recent call last):
  File "/content/YOLOv8-Object-Detection-with-DeepSORT-Tracking/yolo/v8/detect/tracking_vehicle_counting.py", line 310, in predict
    init_tracker()
  File "/content/YOLOv8-Object-Detection-with-DeepSORT-Tracking/yolo/v8/detect/tracking_vehicle_counting.py", line 38, in init_tracker
    deepsort= DeepSort(cfg_deep.DEEPSORT.REID_CKPT,
  File "/content/YOLOv8-Object-Detection-with-DeepSORT-Tracking/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep_sort.py", line 18, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "/content/YOLOv8-Object-Detection-with-DeepSORT-Tracking/yolo/v8/detect/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 14, in __init__
    state_dict = torch.load(model_path, map_location=torch.device(self.device))[
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
**RuntimeError: unexpected EOF, expected 120303 more bytes. The file might be corrupted.**

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Janvi161945** [comment]
Enviroment Iam using is Google Collab
